# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/minahossam/graphis proj/graphisss/ChronoGuardian-game"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/minahossam/graphis proj/graphisss/ChronoGuardian-game"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/minahossam/graphis proj/graphisss/ChronoGuardian-game/CMakeFiles" "/Users/minahossam/graphis proj/graphisss/ChronoGuardian-game//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/minahossam/graphis proj/graphisss/ChronoGuardian-game/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ChronoGuardian

# Build rule for target.
ChronoGuardian: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ChronoGuardian
.PHONY : ChronoGuardian

# fast build rule for target.
ChronoGuardian/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/build
.PHONY : ChronoGuardian/fast

src/AudioManager.o: src/AudioManager.cpp.o
.PHONY : src/AudioManager.o

# target to build an object file
src/AudioManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/AudioManager.cpp.o
.PHONY : src/AudioManager.cpp.o

src/AudioManager.i: src/AudioManager.cpp.i
.PHONY : src/AudioManager.i

# target to preprocess a source file
src/AudioManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/AudioManager.cpp.i
.PHONY : src/AudioManager.cpp.i

src/AudioManager.s: src/AudioManager.cpp.s
.PHONY : src/AudioManager.s

# target to generate assembly for a file
src/AudioManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/AudioManager.cpp.s
.PHONY : src/AudioManager.cpp.s

src/Camera.o: src/Camera.cpp.o
.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/GameObject.o: src/GameObject.cpp.o
.PHONY : src/GameObject.o

# target to build an object file
src/GameObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/GameObject.cpp.o
.PHONY : src/GameObject.cpp.o

src/GameObject.i: src/GameObject.cpp.i
.PHONY : src/GameObject.i

# target to preprocess a source file
src/GameObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/GameObject.cpp.i
.PHONY : src/GameObject.cpp.i

src/GameObject.s: src/GameObject.cpp.s
.PHONY : src/GameObject.s

# target to generate assembly for a file
src/GameObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/GameObject.cpp.s
.PHONY : src/GameObject.cpp.s

src/Input.o: src/Input.cpp.o
.PHONY : src/Input.o

# target to build an object file
src/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Input.cpp.o
.PHONY : src/Input.cpp.o

src/Input.i: src/Input.cpp.i
.PHONY : src/Input.i

# target to preprocess a source file
src/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Input.cpp.i
.PHONY : src/Input.cpp.i

src/Input.s: src/Input.cpp.s
.PHONY : src/Input.s

# target to generate assembly for a file
src/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Input.cpp.s
.PHONY : src/Input.cpp.s

src/Level.o: src/Level.cpp.o
.PHONY : src/Level.o

# target to build an object file
src/Level.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Level.cpp.o
.PHONY : src/Level.cpp.o

src/Level.i: src/Level.cpp.i
.PHONY : src/Level.i

# target to preprocess a source file
src/Level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Level.cpp.i
.PHONY : src/Level.cpp.i

src/Level.s: src/Level.cpp.s
.PHONY : src/Level.s

# target to generate assembly for a file
src/Level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Level.cpp.s
.PHONY : src/Level.cpp.s

src/Level1.o: src/Level1.cpp.o
.PHONY : src/Level1.o

# target to build an object file
src/Level1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Level1.cpp.o
.PHONY : src/Level1.cpp.o

src/Level1.i: src/Level1.cpp.i
.PHONY : src/Level1.i

# target to preprocess a source file
src/Level1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Level1.cpp.i
.PHONY : src/Level1.cpp.i

src/Level1.s: src/Level1.cpp.s
.PHONY : src/Level1.s

# target to generate assembly for a file
src/Level1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Level1.cpp.s
.PHONY : src/Level1.cpp.s

src/Level2.o: src/Level2.cpp.o
.PHONY : src/Level2.o

# target to build an object file
src/Level2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Level2.cpp.o
.PHONY : src/Level2.cpp.o

src/Level2.i: src/Level2.cpp.i
.PHONY : src/Level2.i

# target to preprocess a source file
src/Level2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Level2.cpp.i
.PHONY : src/Level2.cpp.i

src/Level2.s: src/Level2.cpp.s
.PHONY : src/Level2.s

# target to generate assembly for a file
src/Level2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Level2.cpp.s
.PHONY : src/Level2.cpp.s

src/Mesh.o: src/Mesh.cpp.o
.PHONY : src/Mesh.o

# target to build an object file
src/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Mesh.cpp.o
.PHONY : src/Mesh.cpp.o

src/Mesh.i: src/Mesh.cpp.i
.PHONY : src/Mesh.i

# target to preprocess a source file
src/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Mesh.cpp.i
.PHONY : src/Mesh.cpp.i

src/Mesh.s: src/Mesh.cpp.s
.PHONY : src/Mesh.s

# target to generate assembly for a file
src/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Mesh.cpp.s
.PHONY : src/Mesh.cpp.s

src/Model.o: src/Model.cpp.o
.PHONY : src/Model.o

# target to build an object file
src/Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Model.cpp.o
.PHONY : src/Model.cpp.o

src/Model.i: src/Model.cpp.i
.PHONY : src/Model.i

# target to preprocess a source file
src/Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Model.cpp.i
.PHONY : src/Model.cpp.i

src/Model.s: src/Model.cpp.s
.PHONY : src/Model.s

# target to generate assembly for a file
src/Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Model.cpp.s
.PHONY : src/Model.cpp.s

src/ParticleSystem.o: src/ParticleSystem.cpp.o
.PHONY : src/ParticleSystem.o

# target to build an object file
src/ParticleSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/ParticleSystem.cpp.o
.PHONY : src/ParticleSystem.cpp.o

src/ParticleSystem.i: src/ParticleSystem.cpp.i
.PHONY : src/ParticleSystem.i

# target to preprocess a source file
src/ParticleSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/ParticleSystem.cpp.i
.PHONY : src/ParticleSystem.cpp.i

src/ParticleSystem.s: src/ParticleSystem.cpp.s
.PHONY : src/ParticleSystem.s

# target to generate assembly for a file
src/ParticleSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/ParticleSystem.cpp.s
.PHONY : src/ParticleSystem.cpp.s

src/Physics.o: src/Physics.cpp.o
.PHONY : src/Physics.o

# target to build an object file
src/Physics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Physics.cpp.o
.PHONY : src/Physics.cpp.o

src/Physics.i: src/Physics.cpp.i
.PHONY : src/Physics.i

# target to preprocess a source file
src/Physics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Physics.cpp.i
.PHONY : src/Physics.cpp.i

src/Physics.s: src/Physics.cpp.s
.PHONY : src/Physics.s

# target to generate assembly for a file
src/Physics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Physics.cpp.s
.PHONY : src/Physics.cpp.s

src/Player.o: src/Player.cpp.o
.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/Renderer.o: src/Renderer.cpp.o
.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i
.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s
.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/Shader.o: src/Shader.cpp.o
.PHONY : src/Shader.o

# target to build an object file
src/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Shader.cpp.o
.PHONY : src/Shader.cpp.o

src/Shader.i: src/Shader.cpp.i
.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s
.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/Texture.o: src/Texture.cpp.o
.PHONY : src/Texture.o

# target to build an object file
src/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Texture.cpp.o
.PHONY : src/Texture.cpp.o

src/Texture.i: src/Texture.cpp.i
.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s
.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChronoGuardian.dir/build.make CMakeFiles/ChronoGuardian.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ChronoGuardian"
	@echo "... src/AudioManager.o"
	@echo "... src/AudioManager.i"
	@echo "... src/AudioManager.s"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/GameObject.o"
	@echo "... src/GameObject.i"
	@echo "... src/GameObject.s"
	@echo "... src/Input.o"
	@echo "... src/Input.i"
	@echo "... src/Input.s"
	@echo "... src/Level.o"
	@echo "... src/Level.i"
	@echo "... src/Level.s"
	@echo "... src/Level1.o"
	@echo "... src/Level1.i"
	@echo "... src/Level1.s"
	@echo "... src/Level2.o"
	@echo "... src/Level2.i"
	@echo "... src/Level2.s"
	@echo "... src/Mesh.o"
	@echo "... src/Mesh.i"
	@echo "... src/Mesh.s"
	@echo "... src/Model.o"
	@echo "... src/Model.i"
	@echo "... src/Model.s"
	@echo "... src/ParticleSystem.o"
	@echo "... src/ParticleSystem.i"
	@echo "... src/ParticleSystem.s"
	@echo "... src/Physics.o"
	@echo "... src/Physics.i"
	@echo "... src/Physics.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/Shader.o"
	@echo "... src/Shader.i"
	@echo "... src/Shader.s"
	@echo "... src/Texture.o"
	@echo "... src/Texture.i"
	@echo "... src/Texture.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

